FROM php:8.4-apache

ARG BUILD_ARG_ENV=dev
ENV ENV=$BUILD_ARG_ENV
ENV APP_HOME=/var/www/html
ARG HOST_UID=1000
ARG HOST_GID=1000
ENV USERNAME=www-data
ARG INSIDE_DOCKER_CONTAINER=1
ENV INSIDE_DOCKER_CONTAINER=$INSIDE_DOCKER_CONTAINER

# Install PHP-Erweiterungen und Tools
RUN apt-get update && apt-get install -y \
    git zip unzip libicu-dev libonig-dev libzip-dev libpng-dev mariadb-client \
    && docker-php-ext-install intl pdo pdo_mysql zip \
    && rm -rf /tmp/* \
    && rm -rf /var/list/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN pecl install redis && docker-php-ext-enable redis

RUN a2dissite 000-default.conf
RUN rm -r "$APP_HOME"

RUN mkdir -p "$APP_HOME"/public && \
    mkdir -p /home/"$USERNAME" && chown "$USERNAME":"$USERNAME" /home/"$USERNAME" \
    && usermod -o -u "$HOST_UID" "$USERNAME" -d /home/"$USERNAME" \
    && groupmod -o -g "$HOST_GID" "$USERNAME" \
    && chown -R ${USERNAME}:${USERNAME} "$APP_HOME"

COPY docker/app/apache/newsPortal.conf /etc/apache2/sites-available/newsPortal.conf
COPY docker/app/apache/newsPortal-ssl.conf /etc/apache2/sites-available/newsPortal-ssl.conf
RUN a2ensite newsPortal.conf && a2ensite newsPortal-ssl

RUN a2enmod rewrite
RUN a2enmod ssl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN chmod +x /usr/bin/composer


RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout \
    /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem  \
    -subj "/C=DE/ST=Berlin/L=Berlin/O=Security/OU=Development/CN=localhost"

WORKDIR ${APP_HOME}

USER $USERNAME

COPY --chown=${USERNAME}:${USERNAME} ./newsPortal-backend ${APP_HOME}

# TODO: generierung von lexik keys

# install all PHP dependencies
#RUN if [ "$BUILD_ARG_ENV" = "dev" ] || [ "$BUILD_ARG_ENV" = "test" ];  then  \
#      COMPOSER_MEMORY_LIMIT=-1 composer install --optimize-autoloader --no-interaction --no-progress; \
#    else  \
#      export APP_ENV="$BUILD_ARG_ENV"  \
#      && COMPOSER_MEMORY_LIMIT=-1 composer install --optimize-autoloader --no-interaction --no-progress --no-dev; \
#    fi

## create cached config file .env.local.php in case staging/prod environment
#RUN if [ "$BUILD_ARG_ENV" = "staging" ] || [ "$BUILD_ARG_ENV" = "prod" ]; then composer dump-env "$BUILD_ARG_ENV"; \
#    fi

# only for testing
USER root